version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: on-failure
    env_file: .env
    environment:
      - POSTGRES_HOST=db

  db:
    image: postgres:15.1-alpine
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:





